name: Code Coverage

on: [pull_request]

jobs:
  codecov:
    container: 
      image: swift:5.2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --enable-code-coverage
    - id: analysis
      uses: mattpolzin/swift-codecov-action@0.3.0
      with:
        MINIMUM_COVERAGE: 98
    - if: ${{ success() }}
      uses: ouzi-dev/commit-status-updater@v1.0.6
      with:
        status: "success"
        description: "${{ steps.analysis.outputs.codecov }}"
        name: "Test Coverage"
